#### **Задания на повторение материала

Вопрос по предпоследнему заданию-матрицу D ведь нельзя инвертировать так как ее определитель равен нулю из-за того что ранг не равен кол-ву строк. Так?

In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

##### Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [37]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

##### Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [25]:
a1 = a.reshape(2,6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [21]:
a2 = a.reshape(6,2)
a2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [23]:
a3 = a.reshape(3,4)
a3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
a4 = a.reshape(4,3)
a4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [39]:
a5 = a.reshape(12,1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

##### Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [22]:
a6 = a.reshape(2,-1)
a6

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [27]:
a7 = a.reshape(3,-1)
a7

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
a8 = a.reshape(12,-1)
a8

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [31]:
a9 = a.reshape(-1,2)
a9

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [24]:
a10 = a.reshape(-1,3)
a10

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

##### Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? 
Ответ: нет!

In [41]:
a8.ndim

2

##### Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [45]:
a = np.random.randn(3, 4)
a

array([[-0.47557905, -0.07175908,  0.03114396, -0.29682958],
       [ 0.06838073,  1.22160559, -1.15103706,  0.14643258],
       [ 1.34079227, -0.84410389, -0.03759045, -1.05901432]])

In [46]:
a.size

12

In [49]:
b = a.flatten()
b

array([-0.47557905, -0.07175908,  0.03114396, -0.29682958,  0.06838073,
        1.22160559, -1.15103706,  0.14643258,  1.34079227, -0.84410389,
       -0.03759045, -1.05901432])

In [50]:
b.size

12

##### Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [54]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [56]:
a.shape

(10,)

##### Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?
Ответ: а-одномерный массив, b-двухмерный

In [58]:
b = a.reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [59]:
b.shape

(1, 10)

##### Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [71]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
print(a)
print(b)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
10


In [72]:
v = np.concatenate((a, b), axis=0)
print(v)
print('Размер массива v = ',v.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Размер массива v =  10


##### Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [139]:
a = np.arange(0, 12)
print(a)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
#print(A)
#print(At)
print(B)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [129]:
print('Размер матрицы В =', B.shape)
print('Определитель матрицы В =', np.linalg.det(B), 'Обратную матрицу можно посчитать только тогда когда ее определитель отличен от 0.')

Размер матрицы В = (4, 4)
Определитель матрицы В = 0.0 Обратную матрицу можно посчитать только тогда когда ее определитель отличен от 0.


##### Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [116]:
np.random.seed(42)
a = np.random.random()
a

##### Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [140]:
c = np.arange(0, 16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

##### Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [142]:
C = c.reshape(4,4)
D = np.add(B, C.dot(10))
rD = np.linalg.matrix_rank(D)
print('Определитель D=',np.linalg.det(D) ,'ранг D=',rD)
D_inv = np.linalg.inv(D)
D_inv

Определитель D= 5.18953807259442e-26 ранг D= 2


array([[ 4.66062690e+13, -1.49229688e+13, -1.09972869e+14,
         7.82895692e+13],
       [ 1.63480451e+14, -3.81454387e+14,  2.72467419e+14,
        -5.44934838e+13],
       [-4.66779710e+14,  8.07677680e+14, -2.15016230e+14,
        -1.25881740e+14],
       [ 2.56692989e+14, -4.11300324e+14,  5.25216801e+13,
         1.02085655e+14]])

##### Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [145]:
mask_positive = D_inv > 0
mask_negative = D_inv < 0
D_inv[mask_positive] = 1
D_inv[mask_negative] = 0
print(D_inv)
E = np.where(D_inv, B, C)

[[1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 1. 1.]]


In [146]:
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [147]:
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [148]:
print(E)

[[  5   1   2  32]
 [ 14   5  86   7]
 [  8  86  10  11]
 [ 32  13 212 302]]
