#### task 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [2]:
import numpy as np

In [4]:
a = np.array([[1,6], 
              [2,8], 
              [3,11],
              [3,10],
              [1,7]])

In [9]:
np.save('a_centered.npy', ( a - np.load('mean_a.npy')))

In [10]:
np.load('a_centered.npy')

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [15]:
a[:,1]

array([ 6,  8, 11, 10,  7])

In [13]:
a[0,:]

array([1, 6])